AWSTemplateFormatVersion: "2010-09-09"
Transform: AWS::Serverless-2016-10-31
Description: Battle of the Titans - Golang Handler

Parameters:
  ColdStartToken:
    Type: String
    Default: "initial"
    Description: "Token to trigger a configuration update and force a cold start"

Resources:
  GolangTitanFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: GolangTitan
      Description: Golang Lambda for Cold Start Benchmark
      CodeUri: bin/ 
      Handler: bootstrap
      Runtime: provided.al2023
      Architectures:
        - arm64
      MemorySize: 256
      Timeout: 10
      Environment:
        Variables:
          FORCE_COLD_START: !Ref ColdStartToken
